
"use script";window.addEventListener("DOMContentLoaded",()=>{const socialNetworks=document.querySelector(".social-networks"),title=socialNetworks.querySelector(".social-networks__title"),span=socialNetworks.querySelector("span"),iconsFill=socialNetworks.querySelectorAll(".social-networks__icon svg path"),icon=socialNetworks.querySelectorAll(".social-networks__icon"),classPromo=document.querySelector(".promo"),classPromoHeight=window.getComputedStyle(classPromo).height;function changeIconColor(selectorFill,selectorHover,scrollFromTop){if(document.documentElement.scrollTop>=scrollFromTop){selectorFill.classList.remove("fill-white");selectorFill.classList.add("fill-black");selectorHover.classList.add("color-hover");}else{selectorFill.classList.add("fill-white");selectorFill.classList.remove("fill-black");selectorHover.classList.add("colorHover");}}
window.addEventListener("scroll",()=>{if(document.documentElement.scrollTop>=(`${classPromoHeight}`).slice(0,3)-180-230){title.style.color="#000000";}else{title.style.color="#ffffff";}
if(document.documentElement.scrollTop>=(`${classPromoHeight}`).slice(0,3)-90-230){span.style.borderColor="#000000";}else{span.style.borderColor="#ffffff";}
iconsFill.forEach((item,i)=>{if(i==0){changeIconColor(item,icon[0],(`${classPromoHeight}`).slice(0,3)-230);}
if(i==1||i==2){changeIconColor(item,icon[1],(`${classPromoHeight}`).slice(0,3)-25-230);}
if(i==4){changeIconColor(item,icon[2],(`${classPromoHeight}`).slice(0,3)-50-230);}});});const link=document.querySelectorAll("link");let linkLineOne,linkLineTwo,linkLineThree,linkLineFour;link.forEach(item=>{if(item.getAttribute("rel")=="apple-touch-icon"){linkLineOne=item;}else if(item.getAttribute("rel")=="icon"){if(item.getAttribute("sizes")=="32x32"){linkLineTwo=item;}else if(item.getAttribute("sizes")=="16x16"){linkLineThree=item;}}else if(item.getAttribute("rel")=="manifest"){linkLineFour=item;}});function changeFaviconColor(color="orange"){linkLineOne.href=`icons/favicon/${color}/apple-touch-icon.png`;linkLineTwo.href=`icons/favicon/${color}/favicon-32x32.png`;linkLineThree.href=`icons/favicon/${color}/favicon-16x16.png`;linkLineFour.href=`icons/favicon/${color}/site.webmanifest`;}
changeFaviconColor();const arrowUp=document.querySelector(".arrow-up"),arrowUpColor=document.querySelector(".arrow-up-link svg path");window.addEventListener("scroll",()=>{if(window.pageYOffset>=1600){arrowUp.style.display="block";}else{arrowUp.style.display="none";}});function myAnimation(){window.scrollBy(0,-30);if(window.pageYOffset>0){requestAnimationFrame(myAnimation);}}
arrowUp.addEventListener("click",(e)=>{e.preventDefault();requestAnimationFrame(myAnimation);});const hamburger=document.querySelector(".menu-hamburger"),menuClose=document.querySelector(".menu-slide__close"),menu=document.querySelector(".menu-slide"),menuOverlay=document.querySelector(".menu-overlay"),changeColor=document.querySelectorAll(".menu-slide__change-color");hamburger.addEventListener("click",(e)=>{menu.classList.remove("animate__zoomOutLeft");menu.classList.add("menu-active","animate__animated","animate__zoomInLeft");menuOverlay.classList.add("menu-overlay-active");});menuClose.addEventListener("click",(e)=>{menu.classList.remove("menu-active","animate__zoomInLeft");menu.classList.add("animate__animated","animate__zoomOutLeft");menuOverlay.classList.remove("menu-overlay-active");});changeColor.forEach((color,i)=>{color.addEventListener("click",(e)=>{if(color.getAttribute("id")==="orange-color"){document.documentElement.style.setProperty("--main-color","#FFA501");changeFaviconColor("orange");arrowUpColor.style.fill="#FFA501";}else if(color.getAttribute("id")==="green-color"){document.documentElement.style.setProperty("--main-color","#1eb61e");changeFaviconColor("green");arrowUpColor.style.fill="#1eb61e";}else if(color.getAttribute("id")==="yellow-color"){document.documentElement.style.setProperty("--main-color","#dada07");changeFaviconColor("yellow");arrowUpColor.style.fill="#dada07";}else if(color.getAttribute("id")==="purple-color"){document.documentElement.style.setProperty("--main-color","#ac1bac");changeFaviconColor("purple");arrowUpColor.style.fill="#ac1bac";}else if(color.getAttribute("id")==="blue-color"){document.documentElement.style.setProperty("--main-color","#3030f3");changeFaviconColor("blue");arrowUpColor.style.fill="#3030f3";}else if(color.getAttribute("id")==="red-color"){document.documentElement.style.setProperty("--main-color","#e03c3c");changeFaviconColor("red");arrowUpColor.style.fill="#e03c3c";}});});new WOW().init();const carouselSection=document.querySelector(".certificates-carousel");let distance=400,offset=0,num,wrapper=carouselSection.querySelector(".certificates-carousel__slider-wrapper"),inner=carouselSection.querySelector(".certificates-carousel__slider-inner");const sliders=inner.querySelectorAll("img"),arrowLeft=carouselSection.querySelector(".certificates-carousel__arrow-left"),arrowRight=carouselSection.querySelector(".certificates-carousel__arrow-right"),wrapperWidth=window.getComputedStyle(wrapper).width,finish=-(distance*(sliders.length-1));function move(offset){arrowRight.style.opacity="1";arrowLeft.style.opacity="1";if(offset>=0){offset=0;arrowLeft.style.opacity="0.5";}else if(offset<=finish){offset=finish;arrowRight.style.opacity="0.5";}
inner.style.transform=`translateX(${offset + "px"})`;}
move(offset);inner.style.width=100*sliders.length+"%";carouselSection.addEventListener("click",(event)=>{const target=event.target;if(target){if(target.classList.contains("certificates-carousel__arrow-left")){offset+=distance;move(offset);}else if(target.classList.contains("certificates-carousel__arrow-right")){offset-=distance;move(offset);}}});wrapper.innerHTML+=`<div class='certificates-carousel-indicators'></div>`;const indicators=carouselSection.querySelector(".certificates-carousel-indicators");wrapper=carouselSection.querySelector(".certificates-carousel__slider-wrapper");inner=carouselSection.querySelector(".certificates-carousel__slider-inner");for(let i=0;i<sliders.length;i++){indicators.innerHTML+=`<div data-dot=${i+1} class="certificates-carousel-indicators-dot"></div>`;}
const dots=document.querySelectorAll("[data-dot]");dots[0].classList.add("certificates-carousel-indicators_active");dots.forEach((item)=>{item.addEventListener("click",(e)=>{dots.forEach(item=>item.classList.remove("certificates-carousel-indicators_active"));e.target.classList.add("certificates-carousel-indicators_active");num=item.getAttribute('data-dot');offset=(-distance)*(num-1);move(offset);});});const media767px=window.matchMedia("(max-width:767px)"),media1199px=window.matchMedia("(max-width:1199px)"),experience=document.querySelector(".experience"),contactMe=document.querySelector(".contact-me__descr"),skillsMeasureProgressBar=document.querySelectorAll(".skills-measure__progress-bar"),media575px=window.matchMedia("(max-width:575px)");if(media1199px.matches){skillsMeasureProgressBar.forEach(item=>item.setAttribute("data-wow-offset","100"));}
if(media767px.matches){experience.setAttribute("data-wow-offset","50");experience.classList.remove("animate__rotateIn");experience.classList.add("animate__zoomIn");contactMe.setAttribute("data-wow-offset","50");contactMe.classList.remove("animate__lightSpeedInLeft");contactMe.classList.add("animate__zoomIn");}
if(media575px.matches){distance=280;changeSliderSize(distance);}else if(media767px.matches){distance=350;changeSliderSize(distance);}
function changeSliderSize(distance){wrapper.style.width=`${distance}px`;inner.style.width=distance*sliders.length+"px";}
const form=document.querySelector(".contact-me__form"),divName=document.createElement("div"),divEmail=document.createElement("div"),divFormmessage=document.createElement("div"),divForCheckbox=document.createElement("div"),nameInput=form.querySelector("div [name=name]"),emailInput=form.querySelector("div [name=email]"),messageInput=form.querySelector("div [name=message]"),checkboxInput=form.querySelector("div [name=checkbox]"),thanksMassage=document.querySelector("#thanks_massage"),errorMassage=document.querySelector("#error_massage");let sendForm1=false,sendForm2=false,sendForm3=false,sendForm4=false;function messageErrorStyle(input,divmessage,textarea,checkbox){divmessage.style.cssText=`
            position: absolute;
            top: 35px;
            left: 10px;
            font-size: 12px;
            font-weight: 700;
        `;input.style.cssText=`
            border-width: 2px;
            border-color: red;
        `;input.after(divmessage);if(textarea){divmessage.style.cssText+=`
                top: 190px;
                left: 10px;
            `;}
if(checkbox){divForCheckbox.style.cssText+=`
                top: 20px;
            `;}
if(media767px.matches){divmessage.style.cssText=`
            top: 43px;
            font-weight: 700;
            font-size: 12px;

            `;divForCheckbox.textContent="Pls, check this box to proceed";divForCheckbox.style.cssText+=`
                position: absolute;
                top: 33px;
            `;}}
function messageCorrectStyle(input,divmessage,textarea){divmessage.style.cssText=`
            display: none;
        `;input.style.cssText=`
            border-color: #000;
        `;}
form.addEventListener("submit",(e)=>{e.preventDefault();const request=new XMLHttpRequest(),formData=new FormData(form),imgForm=document.createElement("img");imgForm.src="img/form/spinner.svg";imgForm.style.cssText=`
            display:block;
        `;request.open(`POST`,`mailer/smart.php`);const target=e.target;if(nameInput.value){if((nameInput.value.length>=5)&&(nameInput.value.includes(" "))&&((nameInput.value)[nameInput.value.length-1]!==(" "))){sendForm1=true;messageCorrectStyle(nameInput,divName);}
else{divName.textContent="You didnt write your full first and last name";messageErrorStyle(nameInput,divName);sendForm1=false;}}else{divName.textContent="Pls, fill your full name";messageErrorStyle(nameInput,divName);sendForm1=false;}
if(emailInput.value){if(emailInput.value.includes("@")&&(emailInput.value.includes(".com")||emailInput.value.includes(".ru")||emailInput.value.includes(".co.il")||emailInput.value.includes(".uk")||emailInput.value.includes(".gov")||emailInput.value.includes(".net"))){sendForm2=true;messageCorrectStyle(emailInput,divEmail);}
else{divEmail.textContent="Pls,fill your correct Email";messageErrorStyle(emailInput,divEmail);sendForm2=false;}}else{divEmail.textContent="Pls,fill your Email";messageErrorStyle(emailInput,divEmail);sendForm2=false;}
if(messageInput.value){sendForm3=true;messageCorrectStyle(messageInput,divFormmessage,true);}else{divFormmessage.textContent="Pls,fill your message";messageErrorStyle(messageInput,divFormmessage,true);sendForm3=false;}
if(checkboxInput.checked){messageCorrectStyle(checkboxInput,divForCheckbox);sendForm4=true;}else{divForCheckbox.textContent="Pls, check this box if you want to proceed";messageErrorStyle(checkboxInput,divForCheckbox,false,true);sendForm3=false;}
if(sendForm1&&sendForm2&&sendForm3&&sendForm4){form.append(imgForm);form.insertAdjacentElement('afterend',imgForm);request.send(formData);request.addEventListener("readystatechange",(e)=>{if(request.statusText=="OK"){imgForm.remove();thanksMassage.style.display="block";errorMassage.style.display="none";setTimeout(()=>{thanksMassage.style.display="none";},1000);}else{imgForm.remove();thanksMassage.style.display="none";errorMassage.style.display="block";setTimeout(()=>{errorMassage.style.display="none";},10000);}});target.reset();}});const openWindow=document.querySelector(".experience-column__btn"),closeWindow=document.querySelector(".certificates__close"),overlay=document.querySelector(".overlay");openWindow.addEventListener("click",(e)=>{e.preventDefault();overlay.classList.add("overlay_active");});closeWindow.addEventListener("click",(e)=>{e.preventDefault();overlay.classList.remove("overlay_active");});});
